import { 
  Mail,
  Phone,
  MapPin,
  Globe,
  Link,
  Code,
  Terminal,
  Monitor,
  Smartphone,
  Cpu,
  Database,
  Cloud,
  Server,
  Wifi,
  Briefcase,
  GraduationCap,
  Award,
  Book,
  FileText,
  PenTool,
  Edit,
  Camera,
  Video,
  Music,
  Play,
  Pause,
  Heart,
  Star,
  ThumbsUp,
  MessageCircle,
  MessageSquare,
  Send,
  Search,
  Settings,
  User,
  Users,
  Home,
  Calendar,
  Clock,
  Bell,
  Check,
  CheckCircle,
  X,
  XCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  ShoppingCart,
  CreditCard,
  Activity,
  Zap,
  Flame,
  Droplet,
  Sun,
  Moon,
  CloudRain,
  Wind,
  Umbrella,
  Coffee,
  CupSoda,
  Pizza,
  Anchor,
  Compass,
  Map,
  Navigation,
  Truck,
  Plane,
  Rocket,
  Car,
  Smile,
  Frown,
  Meh,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Shield,
  ShieldCheck,
  Folder,
  FolderOpen,
  Archive,
  Box,
  Paperclip,
  Download,
  Upload,
  RefreshCw,
  Maximize,
  Minimize,
  ZoomIn,
  ZoomOut,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Menu,
  MoreHorizontal,
  MoreVertical
} from 'lucide-react';
import { 
  FaGithub,
  FaLinkedin,
  FaTwitter,
  FaInstagram,
  FaYoutube,
  FaFacebook,
  FaTiktok,
  FaDiscord,
  FaTwitch,
  FaWhatsapp,
  FaTelegram,
  FaReddit,
  FaPinterest,
  FaMedium,
  FaDev,
  FaFigma,
  FaCodepen,
  FaDribbble,
  FaBehance,
  FaSpotify,
  FaSoundcloud,
  FaApple,
  FaWindows,
  FaLinux,
  FaNpm,
  FaReact,
  FaVuejs,
  FaAngular,
  FaNodeJs,
  FaPython,
  FaJava,
  FaPhp,
  FaHtml5,
  FaCss3,
  FaGit,
  FaAws,
  FaDocker,
  FaStripe,
  FaPaypal
} from 'react-icons/fa6';

export const IconMap: Record<string, any> = {
  Mail: Mail,
  Phone: Phone,
  MapPin: MapPin,
  Globe: Globe,
  Link: Link,
  Code: Code,
  Terminal: Terminal,
  Monitor: Monitor,
  Smartphone: Smartphone,
  Cpu: Cpu,
  Database: Database,
  Cloud: Cloud,
  Server: Server,
  Wifi: Wifi,
  Briefcase: Briefcase,
  GraduationCap: GraduationCap,
  Award: Award,
  Book: Book,
  FileText: FileText,
  PenTool: PenTool,
  Edit: Edit,
  Camera: Camera,
  Video: Video,
  Music: Music,
  Play: Play,
  Pause: Pause,
  Heart: Heart,
  Star: Star,
  ThumbsUp: ThumbsUp,
  MessageCircle: MessageCircle,
  MessageSquare: MessageSquare,
  Send: Send,
  Search: Search,
  Settings: Settings,
  User: User,
  Users: Users,
  Home: Home,
  Calendar: Calendar,
  Clock: Clock,
  Bell: Bell,
  Check: Check,
  CheckCircle: CheckCircle,
  X: X,
  XCircle: XCircle,
  AlertCircle: AlertCircle,
  AlertTriangle: AlertTriangle,
  Info: Info,
  HelpCircle: HelpCircle,
  ShoppingCart: ShoppingCart,
  CreditCard: CreditCard,
  Activity: Activity,
  Zap: Zap,
  Flame: Flame,
  Droplet: Droplet,
  Sun: Sun,
  Moon: Moon,
  CloudRain: CloudRain,
  Wind: Wind,
  Umbrella: Umbrella,
  Coffee: Coffee,
  CupSoda: CupSoda,
  Pizza: Pizza,
  Anchor: Anchor,
  Compass: Compass,
  Map: Map,
  Navigation: Navigation,
  Truck: Truck,
  Plane: Plane,
  Rocket: Rocket,
  Car: Car,
  Smile: Smile,
  Frown: Frown,
  Meh: Meh,
  Eye: Eye,
  EyeOff: EyeOff,
  Lock: Lock,
  Unlock: Unlock,
  Key: Key,
  Shield: Shield,
  ShieldCheck: ShieldCheck,
  Folder: Folder,
  FolderOpen: FolderOpen,
  Archive: Archive,
  Box: Box,
  Paperclip: Paperclip,
  Download: Download,
  Upload: Upload,
  RefreshCw: RefreshCw,
  Maximize: Maximize,
  Minimize: Minimize,
  ZoomIn: ZoomIn,
  ZoomOut: ZoomOut,
  ArrowRight: ArrowRight,
  ArrowLeft: ArrowLeft,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  ChevronUp: ChevronUp,
  ChevronDown: ChevronDown,
  Menu: Menu,
  MoreHorizontal: MoreHorizontal,
  MoreVertical: MoreVertical,
  Github: FaGithub,
  Linkedin: FaLinkedin,
  Twitter: FaTwitter,
  Instagram: FaInstagram,
  Youtube: FaYoutube,
  Facebook: FaFacebook,
  Tiktok: FaTiktok,
  Discord: FaDiscord,
  Twitch: FaTwitch,
  Whatsapp: FaWhatsapp,
  Telegram: FaTelegram,
  Reddit: FaReddit,
  Pinterest: FaPinterest,
  Medium: FaMedium,
  Dev: FaDev,
  Figma: FaFigma,
  Codepen: FaCodepen,
  Dribbble: FaDribbble,
  Behance: FaBehance,
  Spotify: FaSpotify,
  Soundcloud: FaSoundcloud,
  Apple: FaApple,
  Windows: FaWindows,
  Linux: FaLinux,
  Npm: FaNpm,
  React: FaReact,
  Vuejs: FaVuejs,
  Angular: FaAngular,
  NodeJs: FaNodeJs,
  Python: FaPython,
  Java: FaJava,
  Php: FaPhp,
  Html5: FaHtml5,
  Css3: FaCss3,
  Git: FaGit,
  Aws: FaAws,
  Docker: FaDocker,
  Stripe: FaStripe,
  Paypal: FaPaypal,
};
